# see http://about.travis-ci.org/docs/user/languages/php/ for more hints
language: php

dist: trusty

services:
  - mysql

# list any PHP version you want to test against
php:
  - "7.0"
  - "5.6"

script: phpunit Test.php
