# see http://about.travis-ci.org/docs/user/languages/php/ for more hints
language: php

dist: trusty

services:
  - mysql

before_install: 
- mysql -e 'CREATE DATABASE IF NOT EXISTS fbook;'

php:
  - "7.0"
  - "5.6"

script: phpunit Test.php
